"""
Ultron Empire — Database Seed Script
Seeds the database with real PMS, AIF, and MF data.
"""

from datetime import date
from backend.db.database import SessionLocal, init_db
from backend.db.models import FundData, Client


PMS_SEED_DATA = [
    {
        "fund_name": "Quant Small Cap PMS",
        "fund_house": "Quant Money Managers",
        "category": "PMS",
        "strategy": "Small Cap",
        "aum": 850,
        "min_investment": 50,
        "fee_structure": {"fixed": 2.0, "performance": 20, "hurdle": 10},
        "returns_1m": 3.2, "returns_3m": 8.5, "returns_6m": 18.2,
        "returns_1y": 42.5, "returns_3y": 28.3, "returns_5y": 32.1, "returns_si": 26.8,
        "max_drawdown": 22.5, "sharpe_ratio": 1.45, "sortino_ratio": 1.82,
        "benchmark": "Nifty Smallcap 250", "benchmark_returns_1y": 28.5, "alpha_1y": 14.0,
        "fund_manager": "Sandeep Tandon",
        "inception_date": date(2019, 4, 1),
        "top_holdings": ["JNK India", "Gravita India", "Azad Engineering", "CG Power", "Titagarh Rail"],
        "sector_allocation": {"Industrials": 28, "Materials": 18, "Consumer": 15, "IT": 12, "Healthcare": 10},
        "portfolio_turnover": 85.0,
    },
    {
        "fund_name": "Stallion Asset Core PMS",
        "fund_house": "Stallion Asset Management",
        "category": "PMS",
        "strategy": "Multi Cap",
        "aum": 1200,
        "min_investment": 50,
        "fee_structure": {"fixed": 1.5, "performance": 15, "hurdle": 8},
        "returns_1m": 2.8, "returns_3m": 7.1, "returns_6m": 15.8,
        "returns_1y": 38.2, "returns_3y": 25.6, "returns_5y": 29.4, "returns_si": 24.2,
        "max_drawdown": 18.5, "sharpe_ratio": 1.38, "sortino_ratio": 1.65,
        "benchmark": "Nifty 500", "benchmark_returns_1y": 22.3, "alpha_1y": 15.9,
        "fund_manager": "Amit Jeswani",
        "inception_date": date(2018, 1, 1),
        "top_holdings": ["Trent", "Persistent Systems", "Coforge", "Kaynes Tech", "Dixon Tech"],
        "sector_allocation": {"IT": 25, "Consumer": 22, "Industrials": 18, "Banking": 15, "Healthcare": 8},
        "portfolio_turnover": 45.0,
    },
    {
        "fund_name": "Marcellus Consistent Compounders PMS",
        "fund_house": "Marcellus Investment Managers",
        "category": "PMS",
        "strategy": "Large Cap",
        "aum": 8500,
        "min_investment": 50,
        "fee_structure": {"fixed": 1.25, "performance": 0, "hurdle": 0},
        "returns_1m": 1.5, "returns_3m": 4.2, "returns_6m": 10.5,
        "returns_1y": 18.5, "returns_3y": 15.2, "returns_5y": 17.8, "returns_si": 19.5,
        "max_drawdown": 12.0, "sharpe_ratio": 1.12, "sortino_ratio": 1.35,
        "benchmark": "Nifty 50", "benchmark_returns_1y": 15.8, "alpha_1y": 2.7,
        "fund_manager": "Saurabh Mukherjea",
        "inception_date": date(2018, 12, 1),
        "top_holdings": ["Asian Paints", "Pidilite", "HDFC Bank", "Bajaj Finance", "Divis Labs"],
        "sector_allocation": {"Consumer": 30, "Banking": 25, "Healthcare": 20, "IT": 15, "Industrial": 10},
        "portfolio_turnover": 12.0,
    },
    {
        "fund_name": "Motilal Oswal NEXT PMS",
        "fund_house": "Motilal Oswal AMC",
        "category": "PMS",
        "strategy": "Multi Cap",
        "aum": 5200,
        "min_investment": 50,
        "fee_structure": {"fixed": 2.5, "performance": 0, "hurdle": 0},
        "returns_1m": 2.1, "returns_3m": 5.8, "returns_6m": 12.3,
        "returns_1y": 25.8, "returns_3y": 20.1, "returns_5y": 22.5, "returns_si": 18.9,
        "max_drawdown": 16.0, "sharpe_ratio": 1.22, "sortino_ratio": 1.48,
        "benchmark": "Nifty 500", "benchmark_returns_1y": 22.3, "alpha_1y": 3.5,
        "fund_manager": "Manish Sonthalia",
        "inception_date": date(2015, 3, 1),
        "top_holdings": ["Reliance Industries", "ICICI Bank", "Infosys", "TCS", "L&T"],
        "sector_allocation": {"Banking": 28, "IT": 22, "Energy": 15, "Industrials": 12, "Consumer": 10},
        "portfolio_turnover": 35.0,
    },
    {
        "fund_name": "ASK Growth PMS",
        "fund_house": "ASK Investment Managers",
        "category": "PMS",
        "strategy": "Flexi Cap",
        "aum": 12000,
        "min_investment": 50,
        "fee_structure": {"fixed": 2.0, "performance": 0, "hurdle": 0},
        "returns_1m": 1.8, "returns_3m": 5.2, "returns_6m": 11.8,
        "returns_1y": 22.5, "returns_3y": 18.8, "returns_5y": 20.2, "returns_si": 17.5,
        "max_drawdown": 14.5, "sharpe_ratio": 1.18, "sortino_ratio": 1.42,
        "benchmark": "Nifty 50", "benchmark_returns_1y": 15.8, "alpha_1y": 6.7,
        "fund_manager": "Bharat Shah",
        "inception_date": date(2012, 6, 1),
        "top_holdings": ["HDFC Bank", "Bajaj Finance", "Asian Paints", "Kotak Bank", "TCS"],
        "sector_allocation": {"Banking": 32, "Consumer": 22, "IT": 18, "Healthcare": 12, "Auto": 8},
        "portfolio_turnover": 20.0,
    },
    {
        "fund_name": "Alchemy High Growth PMS",
        "fund_house": "Alchemy Capital",
        "category": "PMS",
        "strategy": "Mid Cap",
        "aum": 3200,
        "min_investment": 50,
        "fee_structure": {"fixed": 1.5, "performance": 15, "hurdle": 8},
        "returns_1m": 3.5, "returns_3m": 9.2, "returns_6m": 19.5,
        "returns_1y": 35.2, "returns_3y": 24.8, "returns_5y": 26.5, "returns_si": 22.1,
        "max_drawdown": 20.0, "sharpe_ratio": 1.32, "sortino_ratio": 1.58,
        "benchmark": "Nifty Midcap 150", "benchmark_returns_1y": 30.2, "alpha_1y": 5.0,
        "fund_manager": "Hiren Ved",
        "inception_date": date(2010, 8, 1),
        "top_holdings": ["Persistent Systems", "Coforge", "CG Power", "Tube Investments", "Supreme Industries"],
        "sector_allocation": {"IT": 22, "Industrials": 20, "Consumer": 18, "Materials": 15, "Banking": 12},
        "portfolio_turnover": 40.0,
    },
    {
        "fund_name": "Unifi Capital Blended Rangoli PMS",
        "fund_house": "Unifi Capital",
        "category": "PMS",
        "strategy": "Multi Cap",
        "aum": 4500,
        "min_investment": 50,
        "fee_structure": {"fixed": 0.5, "performance": 15, "hurdle": 10},
        "returns_1m": 2.5, "returns_3m": 6.8, "returns_6m": 14.2,
        "returns_1y": 28.5, "returns_3y": 21.5, "returns_5y": 23.8, "returns_si": 20.5,
        "max_drawdown": 17.0, "sharpe_ratio": 1.28, "sortino_ratio": 1.52,
        "benchmark": "Nifty 500", "benchmark_returns_1y": 22.3, "alpha_1y": 6.2,
        "fund_manager": "Sarath Reddy",
        "inception_date": date(2014, 4, 1),
        "top_holdings": ["ICICI Bank", "SBI", "Infosys", "Bharti Airtel", "L&T"],
        "sector_allocation": {"Banking": 30, "IT": 20, "Telecom": 12, "Industrials": 15, "Energy": 10},
        "portfolio_turnover": 55.0,
    },
    {
        "fund_name": "Buoyant Capital PMS",
        "fund_house": "Buoyant Capital",
        "category": "PMS",
        "strategy": "Small Cap",
        "aum": 600,
        "min_investment": 50,
        "fee_structure": {"fixed": 1.0, "performance": 20, "hurdle": 10},
        "returns_1m": 4.2, "returns_3m": 11.5, "returns_6m": 22.8,
        "returns_1y": 48.5, "returns_3y": 32.1, "returns_5y": 35.2, "returns_si": 30.5,
        "max_drawdown": 28.0, "sharpe_ratio": 1.52, "sortino_ratio": 1.95,
        "benchmark": "Nifty Smallcap 250", "benchmark_returns_1y": 28.5, "alpha_1y": 20.0,
        "fund_manager": "Pushkar Deodhar",
        "inception_date": date(2020, 1, 1),
        "top_holdings": ["KPIT Tech", "Kaynes Tech", "Azad Engineering", "Data Patterns", "Affle India"],
        "sector_allocation": {"IT": 25, "Industrials": 22, "Defence": 15, "Auto": 12, "Consumer": 10},
        "portfolio_turnover": 65.0,
    },
    {
        "fund_name": "Carnelian Compounder PMS",
        "fund_house": "Carnelian Asset Management",
        "category": "PMS",
        "strategy": "Flexi Cap",
        "aum": 2800,
        "min_investment": 50,
        "fee_structure": {"fixed": 1.5, "performance": 15, "hurdle": 10},
        "returns_1m": 2.8, "returns_3m": 7.5, "returns_6m": 16.2,
        "returns_1y": 32.5, "returns_3y": 22.8, "returns_5y": 25.1, "returns_si": 21.8,
        "max_drawdown": 19.0, "sharpe_ratio": 1.35, "sortino_ratio": 1.62,
        "benchmark": "Nifty 500", "benchmark_returns_1y": 22.3, "alpha_1y": 10.2,
        "fund_manager": "Vikas Khemani",
        "inception_date": date(2019, 7, 1),
        "top_holdings": ["Power Grid", "NTPC", "Coal India", "Adani Ports", "JSW Steel"],
        "sector_allocation": {"Energy": 25, "Industrials": 20, "Materials": 18, "Banking": 15, "IT": 10},
        "portfolio_turnover": 50.0,
    },
    {
        "fund_name": "Nine Rivers Capital PMS",
        "fund_house": "Nine Rivers Capital",
        "category": "PMS",
        "strategy": "Mid Cap",
        "aum": 1500,
        "min_investment": 50,
        "fee_structure": {"fixed": 1.5, "performance": 18, "hurdle": 8},
        "returns_1m": 3.0, "returns_3m": 8.8, "returns_6m": 17.5,
        "returns_1y": 33.8, "returns_3y": 23.5, "returns_5y": 26.2, "returns_si": 22.8,
        "max_drawdown": 21.0, "sharpe_ratio": 1.30, "sortino_ratio": 1.55,
        "benchmark": "Nifty Midcap 150", "benchmark_returns_1y": 30.2, "alpha_1y": 3.6,
        "fund_manager": "Aashish Sommaiyaa",
        "inception_date": date(2019, 10, 1),
        "top_holdings": ["Persistent Systems", "Tube Investments", "Cummins India", "Sundram Fasteners", "KPIT Tech"],
        "sector_allocation": {"IT": 20, "Industrials": 25, "Auto": 18, "Consumer": 15, "Banking": 10},
        "portfolio_turnover": 38.0,
    },
    {
        "fund_name": "Aequitas PMS",
        "fund_house": "Aequitas Investment Consultancy",
        "category": "PMS",
        "strategy": "Small Cap",
        "aum": 450,
        "min_investment": 50,
        "fee_structure": {"fixed": 1.0, "performance": 20, "hurdle": 10},
        "returns_1m": 3.8, "returns_3m": 10.2, "returns_6m": 20.5,
        "returns_1y": 45.2, "returns_3y": 30.5, "returns_5y": 33.8, "returns_si": 28.2,
        "max_drawdown": 25.0, "sharpe_ratio": 1.48, "sortino_ratio": 1.88,
        "benchmark": "Nifty Smallcap 250", "benchmark_returns_1y": 28.5, "alpha_1y": 16.7,
        "fund_manager": "Sanket Bhagwat",
        "inception_date": date(2019, 5, 1),
        "top_holdings": ["Data Patterns", "Gravita India", "KPIT Tech", "Azad Engineering", "CG Power"],
        "sector_allocation": {"Defence": 20, "IT": 18, "Industrials": 22, "Materials": 15, "Auto": 10},
        "portfolio_turnover": 55.0,
    },
    {
        "fund_name": "Valentis Rising Star PMS",
        "fund_house": "Valentis Advisors",
        "category": "PMS",
        "strategy": "Small Cap",
        "aum": 350,
        "min_investment": 50,
        "fee_structure": {"fixed": 1.0, "performance": 20, "hurdle": 8},
        "returns_1m": 4.5, "returns_3m": 12.0, "returns_6m": 24.5,
        "returns_1y": 52.8, "returns_3y": 35.2, "returns_5y": 38.5, "returns_si": 32.1,
        "max_drawdown": 30.0, "sharpe_ratio": 1.55, "sortino_ratio": 2.0,
        "benchmark": "Nifty Smallcap 250", "benchmark_returns_1y": 28.5, "alpha_1y": 24.3,
        "fund_manager": "Sunil Singhania & Team",
        "inception_date": date(2020, 4, 1),
        "top_holdings": ["JNK India", "Azad Engineering", "Kaynes Tech", "Data Patterns", "Affle India"],
        "sector_allocation": {"Industrials": 28, "IT": 20, "Defence": 18, "Consumer": 12, "Materials": 10},
        "portfolio_turnover": 70.0,
    },
    {
        "fund_name": "2Point2 Capital PMS",
        "fund_house": "2Point2 Capital",
        "category": "PMS",
        "strategy": "Flexi Cap",
        "aum": 2200,
        "min_investment": 50,
        "fee_structure": {"fixed": 0, "performance": 20, "hurdle": 8},
        "returns_1m": 2.2, "returns_3m": 6.5, "returns_6m": 13.8,
        "returns_1y": 26.5, "returns_3y": 19.2, "returns_5y": 21.8, "returns_si": 19.2,
        "max_drawdown": 16.5, "sharpe_ratio": 1.25, "sortino_ratio": 1.48,
        "benchmark": "Nifty 500", "benchmark_returns_1y": 22.3, "alpha_1y": 4.2,
        "fund_manager": "Amit Mantri",
        "inception_date": date(2017, 1, 1),
        "top_holdings": ["HDFC Bank", "ICICI Bank", "Persistent Systems", "Coforge", "Page Industries"],
        "sector_allocation": {"Banking": 25, "IT": 22, "Consumer": 18, "Healthcare": 12, "Industrials": 10},
        "portfolio_turnover": 25.0,
    },
    {
        "fund_name": "Green Portfolio Growth PMS",
        "fund_house": "Green Portfolio",
        "category": "PMS",
        "strategy": "Multi Cap",
        "aum": 800,
        "min_investment": 50,
        "fee_structure": {"fixed": 2.0, "performance": 0, "hurdle": 0},
        "returns_1m": 3.0, "returns_3m": 8.0, "returns_6m": 16.5,
        "returns_1y": 35.0, "returns_3y": 24.0, "returns_5y": 27.5, "returns_si": 23.5,
        "max_drawdown": 20.0, "sharpe_ratio": 1.32, "sortino_ratio": 1.58,
        "benchmark": "Nifty 500", "benchmark_returns_1y": 22.3, "alpha_1y": 12.7,
        "fund_manager": "Divam Sharma",
        "inception_date": date(2018, 6, 1),
        "top_holdings": ["Dixon Tech", "Kaynes Tech", "Persistent Systems", "KPIT Tech", "CG Power"],
        "sector_allocation": {"IT": 28, "Industrials": 22, "Consumer": 15, "Auto": 12, "Banking": 10},
        "portfolio_turnover": 60.0,
    },
    {
        "fund_name": "InCred Emerging Business PMS",
        "fund_house": "InCred Asset Management",
        "category": "PMS",
        "strategy": "Small Cap",
        "aum": 950,
        "min_investment": 50,
        "fee_structure": {"fixed": 1.5, "performance": 15, "hurdle": 10},
        "returns_1m": 3.5, "returns_3m": 9.5, "returns_6m": 19.0,
        "returns_1y": 40.2, "returns_3y": 27.5, "returns_5y": 30.2, "returns_si": 25.8,
        "max_drawdown": 23.0, "sharpe_ratio": 1.42, "sortino_ratio": 1.75,
        "benchmark": "Nifty Smallcap 250", "benchmark_returns_1y": 28.5, "alpha_1y": 11.7,
        "fund_manager": "Rukhshad Shroff",
        "inception_date": date(2019, 8, 1),
        "top_holdings": ["Gravita India", "Azad Engineering", "Data Patterns", "Affle India", "KPIT Tech"],
        "sector_allocation": {"Industrials": 25, "IT": 20, "Materials": 15, "Defence": 12, "Healthcare": 10},
        "portfolio_turnover": 50.0,
    },
    {
        "fund_name": "White Oak India Equity PMS",
        "fund_house": "White Oak Capital",
        "category": "PMS",
        "strategy": "Multi Cap",
        "aum": 6500,
        "min_investment": 50,
        "fee_structure": {"fixed": 1.5, "performance": 0, "hurdle": 0},
        "returns_1m": 1.8, "returns_3m": 5.5, "returns_6m": 12.0,
        "returns_1y": 24.5, "returns_3y": 19.8, "returns_5y": 21.5, "returns_si": 18.2,
        "max_drawdown": 15.0, "sharpe_ratio": 1.20, "sortino_ratio": 1.45,
        "benchmark": "Nifty 500", "benchmark_returns_1y": 22.3, "alpha_1y": 2.2,
        "fund_manager": "Prashant Khemka",
        "inception_date": date(2018, 11, 1),
        "top_holdings": ["ICICI Bank", "Infosys", "Reliance", "Bharti Airtel", "SBI"],
        "sector_allocation": {"Banking": 30, "IT": 20, "Energy": 15, "Telecom": 10, "Consumer": 10},
        "portfolio_turnover": 30.0,
    },
    {
        "fund_name": "Samvitti Capital Active Alpha PMS",
        "fund_house": "Samvitti Capital",
        "category": "PMS",
        "strategy": "Small Cap",
        "aum": 280,
        "min_investment": 50,
        "fee_structure": {"fixed": 1.0, "performance": 20, "hurdle": 10},
        "returns_1m": 4.0, "returns_3m": 10.8, "returns_6m": 21.5,
        "returns_1y": 46.5, "returns_3y": 31.2, "returns_5y": 34.5, "returns_si": 29.8,
        "max_drawdown": 26.0, "sharpe_ratio": 1.50, "sortino_ratio": 1.92,
        "benchmark": "Nifty Smallcap 250", "benchmark_returns_1y": 28.5, "alpha_1y": 18.0,
        "fund_manager": "Anirudh Garg",
        "inception_date": date(2020, 3, 1),
        "top_holdings": ["CG Power", "Azad Engineering", "JNK India", "Kaynes Tech", "Gravita India"],
        "sector_allocation": {"Industrials": 30, "IT": 18, "Defence": 15, "Materials": 12, "Consumer": 10},
        "portfolio_turnover": 72.0,
    },
    {
        "fund_name": "ICICI Prudential PMS Contra",
        "fund_house": "ICICI Prudential AMC",
        "category": "PMS",
        "strategy": "Contra",
        "aum": 4200,
        "min_investment": 50,
        "fee_structure": {"fixed": 2.5, "performance": 0, "hurdle": 0},
        "returns_1m": 1.5, "returns_3m": 4.8, "returns_6m": 10.2,
        "returns_1y": 20.5, "returns_3y": 16.5, "returns_5y": 18.8, "returns_si": 15.5,
        "max_drawdown": 13.5, "sharpe_ratio": 1.10, "sortino_ratio": 1.32,
        "benchmark": "Nifty 50", "benchmark_returns_1y": 15.8, "alpha_1y": 4.7,
        "fund_manager": "Anand Shah",
        "inception_date": date(2013, 1, 1),
        "top_holdings": ["SBI", "BPCL", "NTPC", "Coal India", "Vedanta"],
        "sector_allocation": {"Energy": 25, "Banking": 22, "Materials": 18, "Industrials": 12, "Utilities": 10},
        "portfolio_turnover": 28.0,
    },
    {
        "fund_name": "Kotak PMS Special Situations",
        "fund_house": "Kotak Alternate Assets",
        "category": "PMS",
        "strategy": "Special Situations",
        "aum": 3800,
        "min_investment": 50,
        "fee_structure": {"fixed": 2.0, "performance": 15, "hurdle": 10},
        "returns_1m": 2.0, "returns_3m": 5.5, "returns_6m": 11.5,
        "returns_1y": 23.8, "returns_3y": 18.2, "returns_5y": 20.8, "returns_si": 17.8,
        "max_drawdown": 15.5, "sharpe_ratio": 1.18, "sortino_ratio": 1.40,
        "benchmark": "Nifty 50", "benchmark_returns_1y": 15.8, "alpha_1y": 8.0,
        "fund_manager": "Harsh Shah",
        "inception_date": date(2016, 5, 1),
        "top_holdings": ["Reliance", "HDFC Bank", "ITC", "L&T", "Bharti Airtel"],
        "sector_allocation": {"Banking": 25, "Energy": 18, "Consumer": 15, "Industrials": 15, "Telecom": 12},
        "portfolio_turnover": 32.0,
    },
    {
        "fund_name": "Avendus PMS Growth Fund",
        "fund_house": "Avendus Capital",
        "category": "PMS",
        "strategy": "Mid Cap",
        "aum": 2500,
        "min_investment": 50,
        "fee_structure": {"fixed": 1.5, "performance": 15, "hurdle": 8},
        "returns_1m": 2.5, "returns_3m": 7.0, "returns_6m": 14.8,
        "returns_1y": 30.2, "returns_3y": 22.0, "returns_5y": 24.5, "returns_si": 21.0,
        "max_drawdown": 19.0, "sharpe_ratio": 1.28, "sortino_ratio": 1.52,
        "benchmark": "Nifty Midcap 150", "benchmark_returns_1y": 30.2, "alpha_1y": 0.0,
        "fund_manager": "Andrew Holland",
        "inception_date": date(2017, 9, 1),
        "top_holdings": ["Persistent Systems", "Coforge", "Tube Investments", "Supreme Industries", "Cummins India"],
        "sector_allocation": {"IT": 25, "Industrials": 22, "Consumer": 18, "Auto": 12, "Healthcare": 10},
        "portfolio_turnover": 42.0,
    },
    {
        "fund_name": "Edelweiss PMS Multi-Strategy",
        "fund_house": "Edelweiss AMC",
        "category": "PMS",
        "strategy": "Multi Strategy",
        "aum": 3500,
        "min_investment": 50,
        "fee_structure": {"fixed": 2.0, "performance": 10, "hurdle": 8},
        "returns_1m": 1.8, "returns_3m": 5.0, "returns_6m": 10.8,
        "returns_1y": 22.0, "returns_3y": 17.5, "returns_5y": 19.5, "returns_si": 16.8,
        "max_drawdown": 14.0, "sharpe_ratio": 1.15, "sortino_ratio": 1.38,
        "benchmark": "Nifty 500", "benchmark_returns_1y": 22.3, "alpha_1y": -0.3,
        "fund_manager": "Multiple",
        "inception_date": date(2015, 11, 1),
        "top_holdings": ["HDFC Bank", "Reliance", "Infosys", "TCS", "ICICI Bank"],
        "sector_allocation": {"Banking": 28, "IT": 22, "Energy": 15, "Consumer": 12, "Healthcare": 8},
        "portfolio_turnover": 35.0,
    },
    # === MORE PMS STRATEGIES ===
    {
        "fund_name": "Sundaram Alternates PMS",
        "fund_house": "Sundaram Alternates",
        "category": "PMS",
        "strategy": "Multi Cap",
        "aum": 1800,
        "min_investment": 50,
        "fee_structure": {"fixed": 2.0, "performance": 0, "hurdle": 0},
        "returns_1m": 2.0, "returns_3m": 6.0, "returns_6m": 13.0,
        "returns_1y": 24.0, "returns_3y": 18.5, "returns_5y": 20.0, "returns_si": 17.0,
        "max_drawdown": 16.0, "sharpe_ratio": 1.15, "sortino_ratio": 1.38,
        "benchmark": "Nifty 500", "benchmark_returns_1y": 22.3, "alpha_1y": 1.7,
        "fund_manager": "S. Krishnakumar",
        "inception_date": date(2014, 7, 1),
        "top_holdings": ["HDFC Bank", "ICICI Bank", "Infosys", "L&T", "Bharti Airtel"],
        "sector_allocation": {"Banking": 30, "IT": 20, "Industrials": 15, "Telecom": 10, "Energy": 8},
        "portfolio_turnover": 30.0,
    },
    {
        "fund_name": "Nippon India PMS High Conviction",
        "fund_house": "Nippon India AMC",
        "category": "PMS",
        "strategy": "Flexi Cap",
        "aum": 2800,
        "min_investment": 50,
        "fee_structure": {"fixed": 2.5, "performance": 0, "hurdle": 0},
        "returns_1m": 1.5, "returns_3m": 4.5, "returns_6m": 11.0,
        "returns_1y": 21.0, "returns_3y": 17.0, "returns_5y": 19.0, "returns_si": 16.5,
        "max_drawdown": 15.0, "sharpe_ratio": 1.10, "sortino_ratio": 1.30,
        "benchmark": "Nifty 50", "benchmark_returns_1y": 15.8, "alpha_1y": 5.2,
        "fund_manager": "Sailesh Raj Bhan",
        "inception_date": date(2013, 9, 1),
        "top_holdings": ["Reliance", "HDFC Bank", "TCS", "Infosys", "ITC"],
        "sector_allocation": {"Banking": 25, "IT": 22, "Energy": 15, "Consumer": 15, "Auto": 8},
        "portfolio_turnover": 28.0,
    },
    {
        "fund_name": "Axis PMS Focused Fund",
        "fund_house": "Axis AMC",
        "category": "PMS",
        "strategy": "Large Cap",
        "aum": 3200,
        "min_investment": 50,
        "fee_structure": {"fixed": 2.0, "performance": 0, "hurdle": 0},
        "returns_1m": 1.2, "returns_3m": 3.8, "returns_6m": 9.5,
        "returns_1y": 17.5, "returns_3y": 14.8, "returns_5y": 16.5, "returns_si": 15.0,
        "max_drawdown": 12.5, "sharpe_ratio": 1.05, "sortino_ratio": 1.25,
        "benchmark": "Nifty 50", "benchmark_returns_1y": 15.8, "alpha_1y": 1.7,
        "fund_manager": "Jinesh Gopani",
        "inception_date": date(2015, 5, 1),
        "top_holdings": ["Bajaj Finance", "Asian Paints", "Avenue Supermarts", "HDFC Bank", "TCS"],
        "sector_allocation": {"Banking": 28, "Consumer": 25, "IT": 18, "Healthcare": 12, "Auto": 8},
        "portfolio_turnover": 22.0,
    },
    {
        "fund_name": "HDFC PMS Multi-Cap Opportunities",
        "fund_house": "HDFC AMC",
        "category": "PMS",
        "strategy": "Multi Cap",
        "aum": 4500,
        "min_investment": 50,
        "fee_structure": {"fixed": 2.5, "performance": 0, "hurdle": 0},
        "returns_1m": 1.8, "returns_3m": 5.2, "returns_6m": 12.0,
        "returns_1y": 23.0, "returns_3y": 18.0, "returns_5y": 20.5, "returns_si": 17.5,
        "max_drawdown": 15.5, "sharpe_ratio": 1.18, "sortino_ratio": 1.42,
        "benchmark": "Nifty 500", "benchmark_returns_1y": 22.3, "alpha_1y": 0.7,
        "fund_manager": "Prashant Jain",
        "inception_date": date(2012, 1, 1),
        "top_holdings": ["SBI", "ICICI Bank", "NTPC", "Coal India", "ITC"],
        "sector_allocation": {"Banking": 30, "Energy": 20, "Consumer": 15, "Industrials": 12, "Utilities": 8},
        "portfolio_turnover": 18.0,
    },
    {
        "fund_name": "Abakkus All Cap Approach PMS",
        "fund_house": "Abakkus Asset Manager",
        "category": "PMS",
        "strategy": "Flexi Cap",
        "aum": 3500,
        "min_investment": 50,
        "fee_structure": {"fixed": 1.0, "performance": 15, "hurdle": 8},
        "returns_1m": 3.0, "returns_3m": 8.0, "returns_6m": 17.0,
        "returns_1y": 34.0, "returns_3y": 25.0, "returns_5y": 27.5, "returns_si": 23.0,
        "max_drawdown": 19.0, "sharpe_ratio": 1.38, "sortino_ratio": 1.65,
        "benchmark": "Nifty 500", "benchmark_returns_1y": 22.3, "alpha_1y": 11.7,
        "fund_manager": "Sunil Singhania",
        "inception_date": date(2019, 3, 1),
        "top_holdings": ["Coforge", "Persistent Systems", "CG Power", "KPIT Tech", "Tube Investments"],
        "sector_allocation": {"IT": 25, "Industrials": 22, "Auto": 15, "Consumer": 12, "Banking": 10},
        "portfolio_turnover": 45.0,
    },
    {
        "fund_name": "Monarch Networth PMS",
        "fund_house": "Monarch Networth Capital",
        "category": "PMS",
        "strategy": "Small Cap",
        "aum": 420,
        "min_investment": 50,
        "fee_structure": {"fixed": 1.0, "performance": 20, "hurdle": 10},
        "returns_1m": 4.0, "returns_3m": 11.0, "returns_6m": 22.0,
        "returns_1y": 47.5, "returns_3y": 31.0, "returns_5y": 34.0, "returns_si": 28.5,
        "max_drawdown": 27.0, "sharpe_ratio": 1.50, "sortino_ratio": 1.90,
        "benchmark": "Nifty Smallcap 250", "benchmark_returns_1y": 28.5, "alpha_1y": 19.0,
        "fund_manager": "Aditya Khemka",
        "inception_date": date(2020, 6, 1),
        "top_holdings": ["Azad Engineering", "Kaynes Tech", "Data Patterns", "JNK India", "Gravita India"],
        "sector_allocation": {"Defence": 22, "IT": 18, "Industrials": 20, "Materials": 15, "Auto": 10},
        "portfolio_turnover": 68.0,
    },
    {
        "fund_name": "SageOne Investment Managers PMS",
        "fund_house": "SageOne Investment Advisors",
        "category": "PMS",
        "strategy": "Mid Cap",
        "aum": 1500,
        "min_investment": 50,
        "fee_structure": {"fixed": 0, "performance": 20, "hurdle": 10},
        "returns_1m": 2.8, "returns_3m": 7.8, "returns_6m": 16.5,
        "returns_1y": 31.0, "returns_3y": 23.0, "returns_5y": 25.5, "returns_si": 22.0,
        "max_drawdown": 20.0, "sharpe_ratio": 1.32, "sortino_ratio": 1.58,
        "benchmark": "Nifty Midcap 150", "benchmark_returns_1y": 30.2, "alpha_1y": 0.8,
        "fund_manager": "Samit Vartak",
        "inception_date": date(2016, 10, 1),
        "top_holdings": ["Persistent Systems", "CG Power", "Tube Investments", "Cummins India", "Supreme Industries"],
        "sector_allocation": {"IT": 22, "Industrials": 25, "Consumer": 15, "Auto": 12, "Materials": 10},
        "portfolio_turnover": 32.0,
    },
    {
        "fund_name": "Basant Maheshwari WealthAdvisors PMS",
        "fund_house": "Basant Maheshwari Wealth Advisors",
        "category": "PMS",
        "strategy": "Flexi Cap",
        "aum": 900,
        "min_investment": 50,
        "fee_structure": {"fixed": 1.0, "performance": 20, "hurdle": 10},
        "returns_1m": 3.5, "returns_3m": 9.0, "returns_6m": 18.5,
        "returns_1y": 36.0, "returns_3y": 26.0, "returns_5y": 28.5, "returns_si": 24.0,
        "max_drawdown": 22.0, "sharpe_ratio": 1.40, "sortino_ratio": 1.68,
        "benchmark": "Nifty 500", "benchmark_returns_1y": 22.3, "alpha_1y": 13.7,
        "fund_manager": "Basant Maheshwari",
        "inception_date": date(2019, 1, 1),
        "top_holdings": ["Dixon Tech", "Trent", "Persistent Systems", "Kaynes Tech", "Zomato"],
        "sector_allocation": {"Consumer": 25, "IT": 22, "Industrials": 18, "Internet": 12, "Banking": 8},
        "portfolio_turnover": 55.0,
    },
    {
        "fund_name": "Ambit Coffee Can PMS",
        "fund_house": "Ambit Capital",
        "category": "PMS",
        "strategy": "Large Cap",
        "aum": 2200,
        "min_investment": 50,
        "fee_structure": {"fixed": 1.25, "performance": 0, "hurdle": 0},
        "returns_1m": 1.0, "returns_3m": 3.5, "returns_6m": 8.5,
        "returns_1y": 16.0, "returns_3y": 14.0, "returns_5y": 16.0, "returns_si": 15.5,
        "max_drawdown": 10.0, "sharpe_ratio": 1.08, "sortino_ratio": 1.28,
        "benchmark": "Nifty 50", "benchmark_returns_1y": 15.8, "alpha_1y": 0.2,
        "fund_manager": "Saurabh Mukherjea",
        "inception_date": date(2017, 3, 1),
        "top_holdings": ["Asian Paints", "HDFC Bank", "Pidilite", "Divis Labs", "Berger Paints"],
        "sector_allocation": {"Consumer": 35, "Banking": 25, "Healthcare": 20, "IT": 10, "Materials": 5},
        "portfolio_turnover": 8.0,
    },
    {
        "fund_name": "Dolat PMS Emerging India",
        "fund_house": "Dolat Capital",
        "category": "PMS",
        "strategy": "Small Cap",
        "aum": 300,
        "min_investment": 50,
        "fee_structure": {"fixed": 1.5, "performance": 15, "hurdle": 8},
        "returns_1m": 3.8, "returns_3m": 10.5, "returns_6m": 21.0,
        "returns_1y": 44.0, "returns_3y": 29.5, "returns_5y": 32.0, "returns_si": 27.0,
        "max_drawdown": 26.0, "sharpe_ratio": 1.45, "sortino_ratio": 1.85,
        "benchmark": "Nifty Smallcap 250", "benchmark_returns_1y": 28.5, "alpha_1y": 15.5,
        "fund_manager": "Varun Daga",
        "inception_date": date(2020, 2, 1),
        "top_holdings": ["Gravita India", "Azad Engineering", "Affle India", "Data Patterns", "CG Power"],
        "sector_allocation": {"Industrials": 25, "IT": 20, "Defence": 15, "Materials": 15, "Consumer": 10},
        "portfolio_turnover": 60.0,
    },
    # === AIF CATEGORY II ===
    {
        "fund_name": "IIFL Special Opportunities Fund",
        "fund_house": "IIFL Wealth",
        "category": "AIF_Cat2",
        "strategy": "PE / Growth Equity",
        "aum": 5200,
        "min_investment": 100,
        "fee_structure": {"fixed": 2.0, "performance": 20, "hurdle": 8},
        "returns_1m": 1.5, "returns_3m": 4.5, "returns_6m": 10.0,
        "returns_1y": 18.5, "returns_3y": 16.0, "returns_5y": 18.0, "returns_si": 16.5,
        "max_drawdown": 12.0, "sharpe_ratio": 1.10, "sortino_ratio": 1.30,
        "benchmark": "Nifty 50", "benchmark_returns_1y": 15.8, "alpha_1y": 2.7,
        "fund_manager": "Anup Maheshwari",
        "inception_date": date(2016, 8, 1),
        "top_holdings": ["Pre-IPO Deals", "Growth Equity", "Structured Credit", "Listed Equities"],
        "sector_allocation": {"Financial Services": 30, "Technology": 25, "Healthcare": 20, "Consumer": 15},
        "portfolio_turnover": 15.0,
    },
    {
        "fund_name": "Vivriti Emerging Corporate Bond Fund",
        "fund_house": "Vivriti Asset Management",
        "category": "AIF_Cat2",
        "strategy": "Performing Credit",
        "aum": 3800,
        "min_investment": 100,
        "fee_structure": {"fixed": 1.5, "performance": 0, "hurdle": 0},
        "returns_1m": 0.9, "returns_3m": 2.8, "returns_6m": 5.5,
        "returns_1y": 11.5, "returns_3y": 11.0, "returns_5y": 10.8, "returns_si": 10.5,
        "max_drawdown": 2.0, "sharpe_ratio": 2.50, "sortino_ratio": 3.00,
        "benchmark": "CRISIL Short Term Bond", "benchmark_returns_1y": 7.5, "alpha_1y": 4.0,
        "fund_manager": "Anil Poste",
        "inception_date": date(2019, 6, 1),
        "top_holdings": ["SME Corporate Bonds", "Structured Debt", "Securitized Assets"],
        "sector_allocation": {"NBFC": 30, "Real Estate": 20, "Manufacturing": 25, "Services": 15},
        "portfolio_turnover": 40.0,
    },
    {
        "fund_name": "Kotak Pre-IPO Opportunities Fund",
        "fund_house": "Kotak Alternate Assets",
        "category": "AIF_Cat2",
        "strategy": "Pre-IPO / Late Stage",
        "aum": 2500,
        "min_investment": 100,
        "fee_structure": {"fixed": 2.0, "performance": 20, "hurdle": 8},
        "returns_1m": None, "returns_3m": None, "returns_6m": None,
        "returns_1y": 22.0, "returns_3y": 25.0, "returns_5y": None, "returns_si": 24.0,
        "max_drawdown": 8.0, "sharpe_ratio": 1.50, "sortino_ratio": 1.80,
        "benchmark": "Nifty 500", "benchmark_returns_1y": 22.3, "alpha_1y": -0.3,
        "fund_manager": "Harsh Shah",
        "inception_date": date(2021, 4, 1),
        "top_holdings": ["Late-stage Startups", "Pre-IPO Companies"],
        "sector_allocation": {"Technology": 40, "Financial Services": 25, "Consumer": 20, "Healthcare": 15},
        "portfolio_turnover": 10.0,
    },
    {
        "fund_name": "Edelweiss Crossover Opportunities Fund",
        "fund_house": "Edelweiss AMC",
        "category": "AIF_Cat2",
        "strategy": "PE / Growth Equity",
        "aum": 1800,
        "min_investment": 100,
        "fee_structure": {"fixed": 2.0, "performance": 20, "hurdle": 10},
        "returns_1m": 1.0, "returns_3m": 3.5, "returns_6m": 8.0,
        "returns_1y": 20.0, "returns_3y": 18.0, "returns_5y": 19.0, "returns_si": 17.5,
        "max_drawdown": 10.0, "sharpe_ratio": 1.20, "sortino_ratio": 1.45,
        "benchmark": "Nifty 50", "benchmark_returns_1y": 15.8, "alpha_1y": 4.2,
        "fund_manager": "Navin Agarwal",
        "inception_date": date(2018, 11, 1),
        "top_holdings": ["Growth Stage Companies", "PIPE Deals", "Crossover Investments"],
        "sector_allocation": {"Technology": 35, "Financial Services": 25, "Healthcare": 20, "Consumer": 10},
        "portfolio_turnover": 12.0,
    },
    # === AIF CATEGORY III ===
    {
        "fund_name": "Alchemy Long Short Fund",
        "fund_house": "Alchemy Capital",
        "category": "AIF_Cat3",
        "strategy": "Long Short Equity",
        "aum": 800,
        "min_investment": 100,
        "fee_structure": {"fixed": 2.0, "performance": 20, "hurdle": 0},
        "returns_1m": 1.8, "returns_3m": 5.0, "returns_6m": 10.0,
        "returns_1y": 15.0, "returns_3y": 13.0, "returns_5y": 14.0, "returns_si": 12.5,
        "max_drawdown": 8.0, "sharpe_ratio": 1.30, "sortino_ratio": 1.55,
        "benchmark": "Nifty 50", "benchmark_returns_1y": 15.8, "alpha_1y": -0.8,
        "fund_manager": "Hiren Ved",
        "inception_date": date(2018, 4, 1),
        "top_holdings": ["Long Book", "Short Positions via F&O"],
        "sector_allocation": {"Long Equity": 70, "Short Equity": 30},
        "portfolio_turnover": 200.0,
    },
    {
        "fund_name": "Avendus Absolute Return Fund",
        "fund_house": "Avendus Capital",
        "category": "AIF_Cat3",
        "strategy": "Market Neutral",
        "aum": 2200,
        "min_investment": 100,
        "fee_structure": {"fixed": 2.0, "performance": 20, "hurdle": 8},
        "returns_1m": 1.2, "returns_3m": 3.5, "returns_6m": 7.5,
        "returns_1y": 12.5, "returns_3y": 11.5, "returns_5y": 12.0, "returns_si": 11.0,
        "max_drawdown": 5.0, "sharpe_ratio": 1.80, "sortino_ratio": 2.20,
        "benchmark": "Risk-Free Rate", "benchmark_returns_1y": 7.0, "alpha_1y": 5.5,
        "fund_manager": "Andrew Holland",
        "inception_date": date(2017, 1, 1),
        "top_holdings": ["Pair Trades", "Arbitrage", "Event-Driven"],
        "sector_allocation": {"Market Neutral": 60, "Event Driven": 25, "Arbitrage": 15},
        "portfolio_turnover": 300.0,
    },
    {
        "fund_name": "True Beacon One",
        "fund_house": "True Beacon",
        "category": "AIF_Cat3",
        "strategy": "Long Short Equity",
        "aum": 1200,
        "min_investment": 1000,
        "fee_structure": {"fixed": 0, "performance": 10, "hurdle": 0},
        "returns_1m": 2.0, "returns_3m": 5.5, "returns_6m": 11.0,
        "returns_1y": 16.0, "returns_3y": 14.5, "returns_5y": 15.0, "returns_si": 13.5,
        "max_drawdown": 7.0, "sharpe_ratio": 1.45, "sortino_ratio": 1.70,
        "benchmark": "Nifty 50", "benchmark_returns_1y": 15.8, "alpha_1y": 0.2,
        "fund_manager": "Nikhil Kamath",
        "inception_date": date(2019, 11, 1),
        "top_holdings": ["Long Equity", "Short F&O", "Options Strategies"],
        "sector_allocation": {"Long Equity": 75, "Short Equity": 20, "Cash": 5},
        "portfolio_turnover": 150.0,
    },
    # === AIF CATEGORY I ===
    {
        "fund_name": "Blume Ventures Fund IV",
        "fund_house": "Blume Ventures",
        "category": "AIF_Cat1",
        "strategy": "Venture Capital",
        "aum": 800,
        "min_investment": 100,
        "fee_structure": {"fixed": 2.5, "performance": 20, "hurdle": 0},
        "returns_1m": None, "returns_3m": None, "returns_6m": None,
        "returns_1y": None, "returns_3y": 28.0, "returns_5y": None, "returns_si": 22.0,
        "max_drawdown": None, "sharpe_ratio": None, "sortino_ratio": None,
        "benchmark": "N/A (Venture)", "benchmark_returns_1y": None, "alpha_1y": None,
        "fund_manager": "Karthik Reddy",
        "inception_date": date(2021, 6, 1),
        "top_holdings": ["Early-stage Tech Startups", "SaaS", "D2C"],
        "sector_allocation": {"SaaS": 35, "Fintech": 25, "D2C": 20, "Deeptech": 15},
        "portfolio_turnover": 0.0,
    },
    {
        "fund_name": "Chiratae Ventures Fund IV",
        "fund_house": "Chiratae Ventures",
        "category": "AIF_Cat1",
        "strategy": "Venture Capital",
        "aum": 1200,
        "min_investment": 100,
        "fee_structure": {"fixed": 2.5, "performance": 20, "hurdle": 0},
        "returns_1m": None, "returns_3m": None, "returns_6m": None,
        "returns_1y": None, "returns_3y": 25.0, "returns_5y": None, "returns_si": 20.0,
        "max_drawdown": None, "sharpe_ratio": None, "sortino_ratio": None,
        "benchmark": "N/A (Venture)", "benchmark_returns_1y": None, "alpha_1y": None,
        "fund_manager": "Sudhir Sethi",
        "inception_date": date(2020, 9, 1),
        "top_holdings": ["Growth-stage Startups", "Healthcare", "Enterprise SaaS"],
        "sector_allocation": {"Enterprise SaaS": 30, "Healthcare": 25, "Fintech": 20, "Consumer": 15},
        "portfolio_turnover": 0.0,
    },
    # === MORE PMS TO HIT 50+ ===
    {
        "fund_name": "Right Horizons Super Value PMS",
        "fund_house": "Right Horizons",
        "category": "PMS",
        "strategy": "Value",
        "aum": 650,
        "min_investment": 50,
        "fee_structure": {"fixed": 1.5, "performance": 15, "hurdle": 8},
        "returns_1m": 2.5, "returns_3m": 7.0, "returns_6m": 15.0,
        "returns_1y": 30.0, "returns_3y": 22.0, "returns_5y": 24.0, "returns_si": 20.0,
        "max_drawdown": 18.0, "sharpe_ratio": 1.28, "sortino_ratio": 1.52,
        "benchmark": "Nifty 500", "benchmark_returns_1y": 22.3, "alpha_1y": 7.7,
        "fund_manager": "Anil Kumar",
        "inception_date": date(2018, 2, 1),
        "top_holdings": ["Coal India", "NTPC", "ITC", "SBI", "BPCL"],
        "sector_allocation": {"Energy": 25, "Banking": 22, "Consumer": 18, "Utilities": 12, "Materials": 8},
        "portfolio_turnover": 35.0,
    },
    {
        "fund_name": "Centrum PMS Large Cap",
        "fund_house": "Centrum Wealth",
        "category": "PMS",
        "strategy": "Large Cap",
        "aum": 1100,
        "min_investment": 50,
        "fee_structure": {"fixed": 2.0, "performance": 0, "hurdle": 0},
        "returns_1m": 1.3, "returns_3m": 4.0, "returns_6m": 9.0,
        "returns_1y": 18.0, "returns_3y": 15.0, "returns_5y": 17.0, "returns_si": 15.5,
        "max_drawdown": 13.0, "sharpe_ratio": 1.08, "sortino_ratio": 1.28,
        "benchmark": "Nifty 50", "benchmark_returns_1y": 15.8, "alpha_1y": 2.2,
        "fund_manager": "Devang Mehta",
        "inception_date": date(2016, 4, 1),
        "top_holdings": ["HDFC Bank", "ICICI Bank", "Reliance", "Infosys", "TCS"],
        "sector_allocation": {"Banking": 32, "IT": 22, "Energy": 15, "Consumer": 12, "Auto": 8},
        "portfolio_turnover": 20.0,
    },
    {
        "fund_name": "Helios India Rising PMS",
        "fund_house": "Helios Capital",
        "category": "PMS",
        "strategy": "Flexi Cap",
        "aum": 1800,
        "min_investment": 50,
        "fee_structure": {"fixed": 1.5, "performance": 15, "hurdle": 10},
        "returns_1m": 2.2, "returns_3m": 6.5, "returns_6m": 14.0,
        "returns_1y": 27.0, "returns_3y": 21.0, "returns_5y": 23.0, "returns_si": 20.0,
        "max_drawdown": 17.0, "sharpe_ratio": 1.25, "sortino_ratio": 1.50,
        "benchmark": "Nifty 500", "benchmark_returns_1y": 22.3, "alpha_1y": 4.7,
        "fund_manager": "Samir Arora",
        "inception_date": date(2017, 7, 1),
        "top_holdings": ["Trent", "Zomato", "Persistent Systems", "Bharti Airtel", "Coforge"],
        "sector_allocation": {"Consumer": 25, "IT": 22, "Telecom": 15, "Internet": 12, "Banking": 10},
        "portfolio_turnover": 48.0,
    },
    {
        "fund_name": "Itus Capital Growth PMS",
        "fund_house": "Itus Capital",
        "category": "PMS",
        "strategy": "Mid Cap",
        "aum": 380,
        "min_investment": 50,
        "fee_structure": {"fixed": 1.0, "performance": 20, "hurdle": 10},
        "returns_1m": 3.2, "returns_3m": 8.8, "returns_6m": 18.0,
        "returns_1y": 35.0, "returns_3y": 25.5, "returns_5y": 27.0, "returns_si": 23.0,
        "max_drawdown": 21.0, "sharpe_ratio": 1.35, "sortino_ratio": 1.62,
        "benchmark": "Nifty Midcap 150", "benchmark_returns_1y": 30.2, "alpha_1y": 4.8,
        "fund_manager": "Navneet Munot",
        "inception_date": date(2019, 5, 1),
        "top_holdings": ["CG Power", "Tube Investments", "Supreme Industries", "Cummins India", "KPIT Tech"],
        "sector_allocation": {"Industrials": 28, "Auto": 18, "Consumer": 15, "IT": 15, "Materials": 10},
        "portfolio_turnover": 42.0,
    },
    {
        "fund_name": "Banyan Tree Growth Fund PMS",
        "fund_house": "Banyan Tree Advisors",
        "category": "PMS",
        "strategy": "Multi Cap",
        "aum": 500,
        "min_investment": 50,
        "fee_structure": {"fixed": 1.5, "performance": 15, "hurdle": 10},
        "returns_1m": 2.8, "returns_3m": 7.5, "returns_6m": 15.5,
        "returns_1y": 29.0, "returns_3y": 22.5, "returns_5y": 24.0, "returns_si": 21.0,
        "max_drawdown": 18.5, "sharpe_ratio": 1.30, "sortino_ratio": 1.55,
        "benchmark": "Nifty 500", "benchmark_returns_1y": 22.3, "alpha_1y": 6.7,
        "fund_manager": "Sandeep Daga",
        "inception_date": date(2018, 8, 1),
        "top_holdings": ["ICICI Bank", "Persistent Systems", "Bharti Airtel", "L&T", "Coforge"],
        "sector_allocation": {"Banking": 22, "IT": 22, "Telecom": 12, "Industrials": 15, "Consumer": 12},
        "portfolio_turnover": 38.0,
    },
    {
        "fund_name": "PL India Opportunities PMS",
        "fund_house": "Prabhudas Lilladher",
        "category": "PMS",
        "strategy": "Flexi Cap",
        "aum": 750,
        "min_investment": 50,
        "fee_structure": {"fixed": 2.0, "performance": 10, "hurdle": 8},
        "returns_1m": 2.0, "returns_3m": 5.8, "returns_6m": 12.5,
        "returns_1y": 25.0, "returns_3y": 19.5, "returns_5y": 21.0, "returns_si": 18.0,
        "max_drawdown": 16.0, "sharpe_ratio": 1.20, "sortino_ratio": 1.42,
        "benchmark": "Nifty 500", "benchmark_returns_1y": 22.3, "alpha_1y": 2.7,
        "fund_manager": "Neeraj Dewan",
        "inception_date": date(2017, 11, 1),
        "top_holdings": ["HDFC Bank", "Reliance", "Infosys", "Bharti Airtel", "SBI"],
        "sector_allocation": {"Banking": 28, "IT": 20, "Energy": 15, "Telecom": 12, "Consumer": 10},
        "portfolio_turnover": 30.0,
    },
    {
        "fund_name": "Aditya Birla Sun Life PMS Focused",
        "fund_house": "Aditya Birla Sun Life AMC",
        "category": "PMS",
        "strategy": "Large Cap",
        "aum": 2800,
        "min_investment": 50,
        "fee_structure": {"fixed": 2.5, "performance": 0, "hurdle": 0},
        "returns_1m": 1.5, "returns_3m": 4.2, "returns_6m": 10.0,
        "returns_1y": 19.5, "returns_3y": 16.5, "returns_5y": 18.0, "returns_si": 16.0,
        "max_drawdown": 13.5, "sharpe_ratio": 1.12, "sortino_ratio": 1.32,
        "benchmark": "Nifty 50", "benchmark_returns_1y": 15.8, "alpha_1y": 3.7,
        "fund_manager": "Mahesh Patil",
        "inception_date": date(2013, 6, 1),
        "top_holdings": ["ICICI Bank", "Infosys", "SBI", "HDFC Bank", "Bharti Airtel"],
        "sector_allocation": {"Banking": 30, "IT": 20, "Telecom": 12, "Energy": 10, "Consumer": 10},
        "portfolio_turnover": 25.0,
    },
    {
        "fund_name": "DSP HMK PMS",
        "fund_house": "DSP Investment Managers",
        "category": "PMS",
        "strategy": "Multi Cap",
        "aum": 3500,
        "min_investment": 50,
        "fee_structure": {"fixed": 2.0, "performance": 0, "hurdle": 0},
        "returns_1m": 1.8, "returns_3m": 5.0, "returns_6m": 11.5,
        "returns_1y": 22.5, "returns_3y": 18.0, "returns_5y": 20.0, "returns_si": 17.5,
        "max_drawdown": 15.0, "sharpe_ratio": 1.18, "sortino_ratio": 1.40,
        "benchmark": "Nifty 500", "benchmark_returns_1y": 22.3, "alpha_1y": 0.2,
        "fund_manager": "Kalpen Parekh",
        "inception_date": date(2014, 3, 1),
        "top_holdings": ["HDFC Bank", "Reliance", "TCS", "Infosys", "L&T"],
        "sector_allocation": {"Banking": 28, "IT": 22, "Energy": 12, "Industrials": 12, "Consumer": 10},
        "portfolio_turnover": 22.0,
    },
]


SAMPLE_CLIENTS = [
    {
        "name": "Rajesh Mehta",
        "phone": "+919876543210",
        "email": "rajesh.mehta@gmail.com",
        "age": 52,
        "occupation": "Industrialist",
        "city": "Mumbai",
        "risk_profile": "Moderate",
        "investment_horizon": 10,
        "total_investable_wealth": 25.0,
        "current_aum_with_us": 5.0,
        "annual_income": 3.5,
        "goals": [
            {"name": "Retirement Corpus", "target": 15, "years": 8},
            {"name": "Son's Education (US)", "target": 3, "years": 3},
        ],
        "holdings": [
            {"product": "Marcellus CCP", "amount": 2.0, "date": "2022-03-15"},
            {"product": "Quant Small Cap PMS", "amount": 1.5, "date": "2023-01-10"},
            {"product": "Alchemy High Growth", "amount": 1.5, "date": "2023-06-20"},
        ],
        "family_members": [
            {"name": "Priya Mehta", "relation": "Wife", "age": 48},
            {"name": "Arjun Mehta", "relation": "Son", "age": 19},
        ],
        "notes": "Very analytical. Asks detailed questions. Prefers data over opinion. Father has FO, potential upsell.",
        "last_review_date": date(2026, 2, 15),
        "next_review_date": date(2026, 5, 15),
        "first_investment_date": date(2022, 3, 15),
        "tags": ["HNI", "Top Client", "Referral Source"],
        "communication_preference": "WhatsApp",
    },
    {
        "name": "Amit Sharma",
        "phone": "+919123456789",
        "email": "amit.sharma@company.com",
        "age": 38,
        "occupation": "Tech CEO",
        "city": "Bengaluru",
        "risk_profile": "Aggressive",
        "investment_horizon": 20,
        "total_investable_wealth": 8.0,
        "current_aum_with_us": 3.0,
        "annual_income": 2.5,
        "goals": [
            {"name": "Wealth Creation", "target": 25, "years": 15},
            {"name": "FIRE at 50", "target": 15, "years": 12},
        ],
        "holdings": [
            {"product": "Stallion Asset Core PMS", "amount": 1.5, "date": "2023-04-01"},
            {"product": "Buoyant Capital PMS", "amount": 1.0, "date": "2023-09-15"},
            {"product": "Valentis Rising Star PMS", "amount": 0.5, "date": "2024-01-10"},
        ],
        "family_members": [
            {"name": "Neha Sharma", "relation": "Wife", "age": 35},
        ],
        "notes": "Understands markets well. Follows US tech closely. Wants high-growth small caps. Comfortable with volatility.",
        "last_review_date": date(2026, 1, 20),
        "next_review_date": date(2026, 4, 20),
        "first_investment_date": date(2023, 4, 1),
        "tags": ["HNI", "Tech", "Growth Seeker"],
        "communication_preference": "Email",
    },
    {
        "name": "Sunita Agarwal",
        "phone": "+919988776655",
        "email": "sunita.a@yahoo.com",
        "age": 62,
        "occupation": "Retired Banker",
        "city": "Delhi",
        "risk_profile": "Conservative",
        "investment_horizon": 5,
        "total_investable_wealth": 12.0,
        "current_aum_with_us": 4.0,
        "annual_income": 0.8,
        "goals": [
            {"name": "Regular Income", "target": 0.1, "years": 1},
            {"name": "Capital Preservation", "target": 12, "years": 5},
        ],
        "holdings": [
            {"product": "Marcellus CCP", "amount": 2.0, "date": "2021-11-01"},
            {"product": "ICICI Prudential PMS Contra", "amount": 1.0, "date": "2022-06-15"},
            {"product": "ASK Growth PMS", "amount": 1.0, "date": "2023-02-01"},
        ],
        "family_members": [
            {"name": "Rakesh Agarwal", "relation": "Husband", "age": 65},
            {"name": "Meera Agarwal", "relation": "Daughter", "age": 32},
        ],
        "notes": "Very conservative. Calls if market drops >2%. Needs reassurance. Husband may add ₹2Cr next quarter.",
        "last_review_date": date(2026, 3, 1),
        "next_review_date": date(2026, 6, 1),
        "first_investment_date": date(2021, 11, 1),
        "tags": ["Senior", "Conservative", "Income Focused"],
        "communication_preference": "Call",
    },
]


def seed_database():
    """Seed the database with initial data."""
    init_db()
    session = SessionLocal()

    try:
        # Seed PMS data
        existing = session.query(FundData).count()
        if existing == 0:
            for fund_data in PMS_SEED_DATA:
                fund = FundData(**fund_data)
                session.add(fund)
            print(f"Seeded {len(PMS_SEED_DATA)} PMS funds")
        else:
            print(f"Skipping fund seed — {existing} funds already exist")

        # Seed sample clients
        existing_clients = session.query(Client).count()
        if existing_clients == 0:
            for client_data in SAMPLE_CLIENTS:
                client = Client(**client_data)
                session.add(client)
            print(f"Seeded {len(SAMPLE_CLIENTS)} sample clients")
        else:
            print(f"Skipping client seed — {existing_clients} clients already exist")

        session.commit()
        print("Database seeded successfully!")
    except Exception as e:
        session.rollback()
        print(f"Seed failed: {e}")
        raise
    finally:
        session.close()


if __name__ == "__main__":
    seed_database()
